;-------------------------------------------------------------------;
; Vector brief mode settings = F(Options)                           ;
; Procedure 1 of 3 =                                                ;
;           VectorBriefStart, VectorBriefProgress, VectorBriefStop  ;
;                                                                   ;
; INPUT:  Dialogue control block, parameters from OS API            ;
;         RESERVED, input options not used by Vector brief mode     ;
; OUTPUT: Options variables fields, used for benchmarks control     ;
;         RESERVED, input options not used by Vector brief mode     ;
;                                                                   ;
;-------------------------------------------------------------------;

VectorBriefStart:
; Reserved
ret

