;--- Error messages, visualized if can't start application ---

MessageNoCpuid	  DB  'CPUID instruction not supported or locked',0
MessageNoCpuid1   DB  'CPUID function 1 not supported or locked',0
MessageNoTsc      DB  'Time Stamp Counter not supported or locked',0
MessageClkError   DB  'Error measuring TSC frequency',0
MessageMApiError  DB  'Memory information API return error',0
MessageTApiError  DB  'CPU topological information API return error',0
MessageMemError   DB  'Memory allocation error',0
MessageBadWindow  DB  'Error initializing dialogue window',0


