;------------------------------------------------------------------------------;
;     Global Library: connect include files with globally used subroutines.    ; 
;------------------------------------------------------------------------------;

include 'stringwrite.inc'   ; Copy zero-terminated strings, include selectable
include 'decprint.inc'      ; Print integer unsigned 32-bit decimal numbers     
include 'hexprint.inc'      ; Print hex numbers, 4/8/16/32/64-bit
include 'doubleprint.inc'   ; Print double precision floating point numbers 
include 'sizeprint.inc'     ; Print memory size values, Bytes/KB/MB/GB
