;------------------------------------------------------------------------------;
;   This performance patterns used in the "Vector brief" benchmark scenario.   ;
;           Library of performance patterns for mathematics benchmarks:        ;
;                               data definitions.                              ;
;------------------------------------------------------------------------------;
; Reserved. This data type for this module yet not used.
