;------------------------------------------------------------------------------;
;                  This performance patterns used in the                       ; 
;              "Run simple", "Run drawings" benchmark scenarios.               ;
;           Library of performance patterns for latency measurement:           ;
;                               data definitions.                              ;
;------------------------------------------------------------------------------;
; Reserved. This data type for this module yet not used.
