;------------------------------------------------------------------------------;
;                  This performance patterns used in the                       ; 
;              "Run simple", "Run drawings" benchmark scenarios.               ;
;           Library of performance patterns for latency measurement:           ;
;                   variables without pre-defined values.                      ;
;------------------------------------------------------------------------------;
; Reserved. This data type for this module yet not used.