;------------------------------------------------------------------------------;
;              Get system parameters for main window scenario:                 ;
;                  connect include files with subroutines.                     ;
;------------------------------------------------------------------------------;

include 'getsystemparameters.inc'  ; Get and store system information
include 'warningapi.inc'           ; Warning writer for dynamical import
