;------------------------------------------------------------------------------;
;        Data definitions: application name, vendor and version strings.       ;
;------------------------------------------------------------------------------;

PRODUCT_ID   DB  'NUMA CPU&RAM Benchmarks for Win64',0                                    
ABOUT_CAP    DB  'Program info',0
ABOUT_ID     DB  'NUMA CPU&RAM Benchmarks'   , 0Ah,0Dh
             DB  'v1.01.15 for Windows x64'  , 0Ah,0Dh
             DB  '(C)2018 IC Book Labs'      , 0Ah,0Dh,0
